### ISSUE TITLE
这个不支持本地直接运行吗

### ISSUE THREAD

**Issue by Hyper-Beast** [ZCY01/daily_scripts#12]
提示我缺少模块
![image](https://user-images.githubusercontent.com/18001712/120415938-f0f08900-c38e-11eb-85fc-1dc54e7ec336.png)

**Comment by ZCY01** [comment]
需要配合 jd_scripts 脚本使用。

**Comment by ZCY01** [comment]
这个可以修复。

**Comment by Hyper-Beast** [comment]
我把这个加到lxk0301的jd_scripts里然后加上corn任务就可以了是吗

**Comment by Hyper-Beast** [comment]
感谢，我已经搞懂怎么用了

**Comment by Hyper-Beast** [comment]
> 这个可以修复。

请问大佬，这样是不是就可以了
![image](https://user-images.githubusercontent.com/18001712/120417992-5c882580-c392-11eb-8fe7-d3ea89c4b54b.png)
