### ISSUE TITLE
青龙docker拉取任务识别错误

### ISSUE THREAD

**Issue by douzicao** [ZCY01/daily_scripts#17]
开始尝试自动添加定时任务...

Phone; CPU iPhone OS 13_2_3 like Mac OS  -> 添加失败(Unexpected token x in JSON at position 16)
Phone; CPU iPhone OS 14_3 like Mac OS  -> 添加失败(Unexpected token x in JSON at position 16)

**Comment by ZCY01** [comment]
青龙docker是什么环境？我没用过

**Comment by douzicao** [comment]
> 青龙docker是什么环境？我没用过

好吧，之前是好的，那就别研究了，我手动加吧，谢谢了。
