### ISSUE TITLE
价保脚本失效了

### ISSUE THREAD

**Issue by WLy2431217633** [ZCY01/daily_scripts#19]
大佬有空能否解决一下

**Comment by ZCY01** [comment]
试试这个重放版本

**Comment by WLy2431217633** [comment]
> 试试这个重放版本

还是不行呀，一个显示错误，一个显示需要body

**Comment by ZCY01** [comment]
> > 试试这个重放版本
> 
> 还是不行呀，一个显示错误，一个显示需要body

先抓包。点 一键申请

**Comment by WLy2431217633** [comment]
> > > 试试这个重放版本
> > 
> > 
> > 还是不行呀，一个显示错误，一个显示需要body
> 
> 先抓包。点 一键申请

是用qx吗，我是用的容器😂

**Comment by ZCY01** [comment]
> > > > 试试这个重放版本
> > > 
> > > 
> > > 还是不行呀，一个显示错误，一个显示需要body
> > 
> > 
> > 先抓包。点 一键申请
> 
> 是用qx吗，我是用的容器😂

周末再看看。
