### ISSUE TITLE
京东价格保护脚本在surge无法读取到野比大佬的Cookie

### ISSUE THREAD

**Issue by Catnipll** [ZCY01/daily_scripts#3]
1️⃣脚本地址：
https://raw.githubusercontent.com/ZCY01/daily_scripts/main/jd/jd_priceProtect.js

2️⃣surge版本：TF-4.11.0(1905）【最新】

3️⃣问题：
Cookie其实是正常获取的，别的脚本都没问题，京东价格保护脚本可以读取到用户名，但是一直提示cookie已失效。在qx、loon上都是完全正常的，求大佬修复surge🙏🏻

**Comment by ZCY01** [comment]
好了😂害。没注意造成了一个bug...

**Comment by allonmymind** [comment]
我就说好几天运行不了了……原来可以这么联系大佬。不过我的loon获取不到ck了，不知道问题出在哪里……





------------------ 原始邮件 ------------------
发件人: zcy ***@***.***&gt;
发送时间: 2021年4月10日 10:36
收件人: ZCY01/daily_scripts ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZCY01/daily_scripts] 京东价格保护脚本在surge无法读取到野比大佬的Cookie (#3)

**Comment by Catnipll** [comment]
> 好了😂害。没注意造成了一个bug...

好的好的hhhhh，谢谢大佬🙏🏻

**Comment by ZCY01** [comment]
> 我就说好几天运行不了了……原来可以这么联系大佬。不过我的loon获取不到ck了，不知道问题出在哪里……
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: zcy ***@***.***&gt; 发送时间: 2021年4月10日 10:36 收件人: ZCY01/daily_scripts ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[ZCY01/daily_scripts] 京东价格保护脚本在surge无法读取到野比大佬的Cookie (#3)

我没有loon, 我也不知道🤷‍♂️
