### ISSUE TITLE
是PLUS会员，申请专属会员试用商品，仍提示不是会员无法申请

### ISSUE THREAD

**Issue by Wake2020** [ZCY01/daily_scripts#5]
![image](https://user-images.githubusercontent.com/73050843/114820937-62ca3e80-9df2-11eb-9f67-b646d98175a6.png)

大佬，顺便提个小建议，就是增加试用的份数筛选机制，一个商品，提供数量超过20的，基本都是垃圾，经常会踩到价格很高，份数提供很多的垃圾东西。

**Comment by ZCY01** [comment]
这个会员是指店铺会员，不是PLUS会员。份数塞选可以添加。
